spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    ignore-migration-patterns: "*:*"
jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}