spring:
  application:
    scheduler:
      zone: ${SCHEDULER_ZONE}
      crone: ${SCHEDULER_CRONE}
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    topic-name: ${KAFKA_TOPIC_NAME}
    partitions-count: ${KAFKA_PARTITIONS_COUNT}
    replication-count: ${KAFKA_REPLICATIONS_COUNT}