spring:
  kafka:
    bootstrap-servers: ${KAFKA_PORT_EXT}
    producer:
      key-serializer: ${KAFKA_KEY_SERIALIZER}
      value-serializer: ${KAFKA_VALUE_SERIALIZER}
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    topic-name: ${KAFKA_TOPIC_NAME}
    partitions-count: ${KAFKA_PARTITIONS_COUNT}
    replication-count: ${KAFKA_REPLICATIONS_COUNT}
  application:
    name: todo_app
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    ignore-migration-patterns: "*:*"
app:
  jwt:
    config:
      lifetime-token: 30m
      secret-key: "***REMOVED***"