spring:
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      acks: 1
      spring:
        json:
          add:
            type:
              headers: false
    topic-name: "EMAIL_SENDING_TASKS"
    partitions-count: 3
    replication-count: 1
  application:
    name: todo_app
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    ignore-migration-patterns: "*:*"
app:
  jwt:
    config:
      lifetime-token: 30m
      secret-key: ${SECRET_KEY}
